# Generated by Django 5.2.6 on 2025-09-05 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='data_criacao',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='data_prazo',
            new_name='deadline_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='titulo',
            new_name='title',
        ),
    ]
